# Generated by Django 5.1.12 on 2026-02-08 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("WEB", "Web (B2C)"), ("INTERNO", "Interno (B2B)")],
                        default="WEB",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Solo aplica si está logueado; no puede dejar precio bajo costo (salvo OWNER).",
                        max_digits=5,
                        verbose_name="Descuento %",
                    ),
                ),
                (
                    "is_internal_active",
                    models.BooleanField(
                        default=True, verbose_name="Cliente interno activo"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("rut", models.CharField(blank=True, default="", max_length=20)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de cliente",
                "verbose_name_plural": "Perfiles de cliente",
            },
        ),
    ]
