# Generated by Django 5.1.12 on 2026-02-09 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprofile",
            options={},
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="warranty_days_modifier",
            field=models.IntegerField(
                default=0,
                help_text="Modifica la garantía estándar. Ej: -7 acorta 7 días. 0 = sin cambio.",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="customer_type",
            field=models.CharField(
                choices=[("WEB", "Cliente Web"), ("INTERNO", "Cliente Interno")],
                default="WEB",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ej: 10.00 = 10% descuento.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="is_internal_active",
            field=models.BooleanField(
                default=True,
                help_text="Permite desactivar el acceso interno sin borrar el cliente.",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Solo los clientes internos necesitan usuario para iniciar sesión.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
