# Generated by Django 5.1.12 on 2026-02-14 04:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PENDING_PAYMENT", "Pendiente de pago"),
                            ("PAID", "Pagado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "delivery_method",
                    models.CharField(default="DELIVERY", max_length=20),
                ),
                ("region", models.CharField(blank=True, default="", max_length=80)),
                ("comuna", models.CharField(blank=True, default="", max_length=80)),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "address_reference",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                ("subtotal", models.PositiveIntegerField(default=0)),
                ("shipping_cost", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("slug", models.CharField(blank=True, default="", max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("unit_price", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("line_total", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.order",
                    ),
                ),
            ],
        ),
    ]
