# Generated by Django 5.1.12 on 2026-02-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, default="", max_length=20, unique=True),
        ),
    ]
