# Generated by Django 5.1.12 on 2026-02-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_add_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="webpay_authorization_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="webpay_card_last4",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="order",
            name="webpay_payment_type",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="webpay_response_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="webpay_status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="webpay_token",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
