# Generated by Django 6.0.1 on 2026-01-28 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("stock_minimum_alert", models.PositiveIntegerField(default=3)),
                (
                    "euro_norm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EURO3", "Euro 3"),
                            ("EURO4", "Euro 4"),
                            ("EURO5", "Euro 5"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACERO", "Acero"),
                            ("INOX", "Acero inoxidable"),
                            ("CERAMICO", "Cerámico"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "install_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLUG_PLAY", "Plug & Play"),
                            ("SOLDADURA", "Requiere soldadura"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quality_score", models.PositiveIntegerField(default=0)),
                ("is_publishable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/%Y/%m/%d/")),
                ("alt_text", models.CharField(blank=True, default="", max_length=160)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="catalog.vehiclebrand",
                    ),
                ),
            ],
            options={
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="VehicleEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GASOLINA", "Gasolina"),
                            ("DIESEL", "Diésel"),
                            ("HIBRIDO", "Híbrido"),
                            ("EV", "EV"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engines",
                        to="catalog.vehiclemodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("model", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProductCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_from", models.PositiveIntegerField()),
                ("year_to", models.PositiveIntegerField()),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GASOLINA", "Gasolina"),
                            ("DIESEL", "Diésel"),
                            ("HIBRIDO", "Híbrido"),
                            ("EV", "EV"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        default="ALTA",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilities",
                        to="catalog.product",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.vehiclebrand",
                    ),
                ),
                (
                    "engine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.vehicleengine",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.vehiclemodel",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["brand", "model", "year_from", "year_to"],
                        name="catalog_pro_brand_i_52b9b3_idx",
                    ),
                    models.Index(
                        fields=["product", "is_active"],
                        name="catalog_pro_product_d4b9db_idx",
                    ),
                ],
            },
        ),
    ]
