# Generated by Django 5.1.12 on 2026-02-02 11:43

from django.db import migrations, models


def assign_image_positions(apps, schema_editor):
    """Asigna posición 1-4 a imágenes existentes; elimina las que excedan 4 por producto."""
    ProductImage = apps.get_model("catalog", "ProductImage")
    for product_id in (
        ProductImage.objects.values_list("product_id", flat=True).distinct()
    ):
        images = list(
            ProductImage.objects.filter(product_id=product_id).order_by("id")
        )
        for idx, img in enumerate(images[:4]):
            img.position = idx + 1
            img.save()
        for img in images[4:]:
            img.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["product", "position"]},
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Volumen en litros o m³ según convención",
                max_digits=10,
                null=True,
                verbose_name="Volumen",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Peso en kilogramos",
                max_digits=10,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Orden de la imagen para este producto (máximo 4 imágenes).",
                verbose_name="Posición (1-4)",
            ),
        ),
        migrations.RunPython(assign_image_positions, noop),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Precio de compra",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1), ("position__lte", 4)),
                name="productimage_position_1_to_4",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                fields=("product", "position"), name="unique_product_image_position"
            ),
        ),
    ]
