# Generated by Django 5.1.12 on 2026-02-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_add_product_weight_volume_and_image_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categorías"},
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Alto en centímetros",
                max_digits=10,
                null=True,
                verbose_name="Alto (cm)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Largo en centímetros",
                max_digits=10,
                null=True,
                verbose_name="Largo (cm)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ancho en centímetros",
                max_digits=10,
                null=True,
                verbose_name="Ancho (cm)",
            ),
        ),
    ]
