# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_add_product_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ficha_tecnica",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Texto con ficha técnica, certificaciones y especificaciones. Si está vacío, se muestran solo los campos técnicos estándar.",
                verbose_name="Ficha técnica / Descripción",
            ),
        ),
    ]
