# Generated by Django 5.1.12 on 2026-02-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_ficha_tecnica"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="default_warranty_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Si está vacío, se usa la garantía global.",
                null=True,
                verbose_name="Días de garantía por defecto",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="default_warranty_terms",
            field=models.TextField(
                blank=True, default="", verbose_name="Términos de garantía por defecto"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="has_warranty",
            field=models.BooleanField(default=True, verbose_name="Tiene garantía"),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Si está vacío, se usa categoría o valor global.",
                null=True,
                verbose_name="Días de garantía",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_terms",
            field=models.TextField(
                blank=True, default="", verbose_name="Términos de garantía"
            ),
        ),
    ]
