# Generated by Django 5.1.12 on 2026-02-09 02:53

import apps.catalog.utils.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_add_warranty_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.catalog.utils.media_paths.product_image_upload_to
            ),
        ),
    ]
