# Generated by Django 5.1.12 on 2026-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_image_upload_to_by_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio normal para mostrar tachado y calcular descuento. Si está vacío no se muestra oferta.",
                max_digits=12,
                null=True,
                verbose_name="Precio anterior / comparar",
            ),
        ),
    ]
