# Generated by Django 5.1.12 on 2026-02-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_add_compare_at_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="euro_norm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EURO2", "Euro 2"),
                    ("EURO3", "Euro 3"),
                    ("EURO4", "Euro 4"),
                    ("EURO5", "Euro 5"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
