# Generated by Django 5.1.12 on 2026-02-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_euro_norm"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku_canonico",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SKU normalizado para matching con zip, imágenes y reportes. No cambiar el SKU visible.",
                max_length=60,
                null=True,
                verbose_name="SKU canónico",
            ),
        ),
    ]
