# Generated by Django 5.1.12 on 2026-02-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_backfill_sku_canonico"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="celdas",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Densidad de celdas (ej. 200 CPSI)",
                null=True,
                verbose_name="Celdas (CPSI)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="combustible",
            field=models.CharField(
                blank=True,
                choices=[("BENCINA", "Bencina"), ("DIESEL", "Diesel")],
                max_length=20,
                null=True,
                verbose_name="Combustible",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="diametro_entrada",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Diámetro de entrada en pulgadas (ej. 2.5)",
                max_digits=5,
                null=True,
                verbose_name="Diámetro entrada (pulg.)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="diametro_salida",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Diámetro salida (pulg.)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="largo_mm",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Largo total en milímetros",
                null=True,
                verbose_name="Largo (mm)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tiene_sensor",
            field=models.BooleanField(default=False, verbose_name="Con sensor O2"),
        ),
    ]
