# Generated by Django 5.1.12 on 2026-02-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_add_cataliticos_technical_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductViewStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("last_viewed", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_stat",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de vistas",
                "verbose_name_plural": "Estadísticas de vistas",
                "ordering": ["-views"],
            },
        ),
    ]
