# Generated by Django 5.1.12
# Ajustada para ser idempotente: añade columnas solo si no existen (evita duplicate column).

from django.db import migrations, models


def add_cc_columns_if_missing(apps, schema_editor):
    """Añade recommended_cc_min y recommended_cc_max solo si no existen."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(catalog_product)")
        columns = [row[1] for row in cursor.fetchall()]
    if "recommended_cc_min" not in columns:
        schema_editor.execute(
            "ALTER TABLE catalog_product ADD COLUMN recommended_cc_min INTEGER NULL;"
        )
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS catalog_product_recommended_cc_min_idx "
            "ON catalog_product (recommended_cc_min);"
        )
    if "recommended_cc_max" not in columns:
        schema_editor.execute(
            "ALTER TABLE catalog_product ADD COLUMN recommended_cc_max INTEGER NULL;"
        )
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS catalog_product_recommended_cc_max_idx "
            "ON catalog_product (recommended_cc_max);"
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_add_engine_displacement_support"),
    ]

    operations = [
        migrations.RunPython(add_cc_columns_if_missing, noop_reverse),
        # StateOnly: actualizar el estado de migraciones sin tocar la BD (las columnas ya están)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="recommended_cc_min",
                    field=models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Rango de cilindrada para catalíticos: el vehículo debe tener cc >= este valor.",
                        null=True,
                        verbose_name="Cilindrada mínima recomendada (cc)",
                    ),
                ),
                migrations.AddField(
                    model_name="product",
                    name="recommended_cc_max",
                    field=models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Rango de cilindrada para catalíticos: el vehículo debe tener cc <= este valor.",
                        null=True,
                        verbose_name="Cilindrada máxima recomendada (cc)",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
