# Generated by Django 5.1.12 on 2026-03-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_merge_0017_0021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
